# Source: https://github.com/argoproj/argocd-example-apps/tree/master/kustomize-guestbook

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- guestbook-ingress.yaml
- redis-leader-deployment.yaml
- redis-leader-svc.yaml
- redis-follower-deployment.yaml
- redis-follower-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
